@Webhook_Api_HostAddress = https://localhost:7248

### Create order

POST {{Webhook_Api_HostAddress}}/orders
Content-Type: application/json

{
    "customerName": "string",
    "amount": 123
}

### Create subscription

POST {{Webhook_Api_HostAddress}}/webhooks/subscriptions
Content-Type: application/json

{
    "eventType": "order.created",
    "webhookUrl": "https://webhook-test.com/e34fd95db865ac86b05ad30f49dc41a7"
}
