@Webhook_Api_HostAddress = https://localhost:7248

### Create order

POST {{Webhook_Api_HostAddress}}/orders
Content-Type: application/json

{
    "customerName": "string",
    "amount": 123
}

### Create subscription

POST {{Webhook_Api_HostAddress}}/webhooks/subscriptions
Content-Type: application/json

{
    "eventType": "order.created",
    "webhookUrl": "https://webhook.site/9744bf7c-d416-411e-8bcc-35211d240e5b"
}
